config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/users/:id/reviews', to: 'users#reviews', as: 'users_reviews'
  get '/users/:id/highest_rated_books', to: 'users#highest_rated_books', as: 'users_highest_rated_books'
  get '/users/:id/lowest_rated_books', to: 'users#lowest_rated_books', as: 'users_lowest_rated_books'

  resources :books do
    resources :reviews
  end

  resources :book_lists do
    resources :books, only: [:create, :destroy, :new, :edit, :update]
  end

  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/book_list.rb
class BookList < ApplicationRecord
  belongs_to :user
  has_many :book_features
  has_many :books, :through => :book_features
  validates :title, :presence => true

  def books_attributes=(book_attributes)
    book_attributes.values.each do |book_attribute|
    if book_attribute[:title].present?
        genre = Genre.find_or_create_by(name: book_attribute[:genre])
        author = Author.find_or_create_by(name: book_attribute[:author])
        book = Book.find_or_create_by(title: book_attribute[:title], genre: genre, author: author)
          if !self.books.include?(book)
            self.books << book
          end
        end
      end
    end

  def book_ids=(ids)
    ids.each do |id|
      book = Book.find_by(id: id)
      if !self.books.include?(book)
        self.books << book
      end
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  validates :name, presence: true
  before_validation :make_title_case
  scope :alphabatize, -> { order('name asc') }

  def make_title_case
    self.name = self.name.titlecase
  end

end

app/controllers/book_lists_controller.rb
class BookListsController < ApplicationController
  before_action :set_current_user

  def index
    authorize! :read, BookList
    @booklists = current_user.book_lists
  end

  def new
    authorize! :create, BookList
    @booklist = BookList.new
  end

  def create
    @booklist = BookList.create(book_list_params)
    authorize! :create, BookList
    if @booklist.save
      update_book_statuses
      redirect_to book_list_path(@booklist)
    else
      render :new
    end
  end

  def show
    @booklist = BookList.find_by(id: params[:id])
    authorize! :read, @booklist
  end

  def edit
    @booklist = BookList.find_by(id: params[:id])
  end

  def update
    @booklist = BookList.find_by(id: params[:id])
    authorize! :update, @booklist
    @booklist.update(book_list_params)
    update_book_statuses
    redirect_to book_list_path(@booklist)
  end

  def destroy
    @booklist = BookList.find_by(id: params[:id])
    authorize! :destroy, @booklist
    @booklist.destroy
    redirect_to book_lists_path
  end

  private
   def book_list_params
     params.require(:book_list).permit(:title, :user_id, :book_ids => [], :books_attributes => [:title, :genre, :author], :book_features => [])
   end

   def set_current_user
     @user = current_user
   end

   def update_book_statuses
    if params[:book_list][:book_ids].present?
        params[:book_list][:book_ids].each do |book|
          new_book = Book.find_by(id: book)
          new_book.update_status(params[:book_list][:book_features], book_list_id: @booklist.id)
        end
      end
    if params[:book_list][:books_attributes].present? && !params[:book_list][:books_attributes]["0"][:title].empty?
      book = Book.find_by(title: params[:book_list][:books_attributes]["0"][:title].titleize)
      book.update_status(params[:book_list][:book_features], book_list_id: @booklist.id)
    end
  end

end

app/helpers/book_lists_helper.rb
module BookListsHelper
end

app/views/book_lists/_footer.html.erb
<strong>
  <%= link_to "Add A Review", new_book_review_path(book.id) %><br>
  <%= link_to "Update Status", edit_book_list_book_path(booklist.id, book.id) %><br>
  <%= link_to "Delete from booklist", book_list_book_path(booklist.id, book.id), :method => "delete" %>
</strong>

app/views/book_lists/_form.html.erb
<%= form_for booklist do |f| %>

<%= f.label "Title: " %>
<%= f.text_field :title %><br><br>

Select a book to add to this book list:<br><br>
<%= f.collection_check_boxes :book_ids, Book.alphabatize, :id, :title, :checked => false, :include_hidden => false do |b| %>
  <%= b.check_box %><%= b.label %><br>
<% end %><br>

Create a book to add to this book list:<br><br>
<%= f.fields_for :books, booklist.books.build do |book_fields| %>
  Title:<br><%= book_fields.text_field :title %><br><br>
  Author:<br><%= book_fields.text_field :author %><br><br>
  Genre:<br><%= book_fields.text_field :genre %><br><br>
<% end %>

<%= f.label "Status" %><br>
<%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%><br><br>

<%= f.hidden_field :user_id, :value => user.id %>
<%= f.submit %>
<% end %>

app/views/book_lists/_header.html.erb
<center>
  <h1>"<%= booklist.title %>"</h1>
    <strong>
      <%= link_to "Add a book to this booklist", new_book_list_book_path(booklist) %><br>
      <%= link_to "Edit this booklist", edit_book_list_path(booklist) %><br>
      <%= link_to "Delete this entire booklist", book_list_path(booklist.id), :method => "delete" %>
    </strong>
</center>

app/views/book_lists/edit.html.erb
<%= render partial: 'layouts/errors', locals: {object: @booklist} %>

<h1>Edit <%= @booklist.title %></h1>
<%= render partial: 'form', locals: {booklist: @booklist, user: @user} %>

app/views/book_lists/index.html.erb
<h2>Your Current Book Lists</h2>
<% if @booklists.present? %>
  <% @booklists.each do |book_list| %>
    <h3>Title: <%= link_to book_list.title, book_list_path(book_list) %></h3>
    Books on this list:
    <ol>
      <% book_list.books.each do |book| %>
        <li><%= link_to book.title, book_path(book) %></li>
        Status: <%= book.book_features.find_by(book_list_id: book_list.id).status %><br><br>
      <% end %>
    </ol>
  <% end %>
<% else %>
  <%= link_to "Get started by creating a book list", new_book_list_path %>
<% end %>

app/views/book_lists/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @booklist} %>

<h2>Create A New Book List</h2>
<%= render partial: 'form', locals: {booklist: @booklist, user: @user} %>

app/views/book_lists/show.html.erb
<%= render partial: 'header', locals: {booklist: @booklist} %>

<% @booklist.books.each do |book| %>
  <hr>
    <h3> Title: <%= link_to book.title.titleize, book_path(book) %><br></h3>
    Author: <%= link_to book.author.name, author_path(book.author) %><br>
    Genre: <%= link_to book.genre.name, genre_path(book.genre) %><br>
    Status: <%= book.book_features.find_by(book_list_id: @booklist.id).status %><br><br>

    <%= render partial: 'footer', locals: {booklist: @booklist, book: book} %>
<% end %>