config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/users/:id/reviews', to: 'users#reviews', as: 'users_reviews'
  get '/users/:id/highest_rated_books', to: 'users#highest_rated_books', as: 'users_highest_rated_books'
  get '/users/:id/lowest_rated_books', to: 'users#lowest_rated_books', as: 'users_lowest_rated_books'

  resources :books do
    resources :reviews
  end

  resources :book_lists do
    resources :books, only: [:create, :destroy, :new, :edit, :update]
  end

  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :book_lists
  has_many :reviews

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def books
    users_books = []
    BookList.where(user_id: self.id).each do |booklist|
        booklist.books.each do |book|
          users_books << book
      end
    end
    users_books
  end

  def books_by_status(status)
    books_by_status = []
    BookList.where(user_id: self.id).each do |booklist|
      BookFeature.where(book_list_id: booklist.id).each do |book|
        if book.status == "#{status}"
          new_book = Book.find_by(id: book.book_id)
          books_by_status << new_book
        end
      end
    end
    books_by_status
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def reviews
    @user = User.find_by_id(params[:id])
    authorize! :show_reviews_for, @user
    @reviews = @user.reviews
    render 'users/reviews'
  end

  def highest_rated_books
    @user = User.find_by_id(params[:id])
    authorize! :show_highest_rated_books_for, @user
    @books = Book.highest_rated_books.by_user(@user)
  end

  def lowest_rated_books
    @user = User.find_by_id(params[:id])
    authorize! :show_lowest_rated_books_for, @user
    @books = Book.lowest_rated_books.by_user(@user)
  end
end

app/views/users/_book_collection.html.erb
<ul>
  <% books.each do |book| %>
    <li><%= link_to book.title, book_path(book.id) %></li>
    Rating: <%= book.reviews.find_by(book_id: book.id, user_id: current_user.id).rating %><br><br>
<% end %>
</ul>

app/views/users/highest_rated_books.html.erb
<h2>Your Highest Rated Books</h1>
<%= render partial: "book_collection", locals: {books: @books} %>

app/views/users/lowest_rated_books.html.erb
<h2>Your Lowest Rated Books</h2>
<%= render partial: "book_collection", locals: {books: @books} %>

app/views/users/reviews.html.erb
<center>
  <h2>Reviews You Have Written</h2>
</center>

<% if @reviews.present? %>
  <% @reviews.each do |review| %>
    <h3>Title: "<%= link_to review.title, book_review_path(review.book, review.id) %>"</h3>
    <strong>Book:</strong> <%= link_to review.book.title, book_path(review.book) %><br>
    <strong>Stars: </strong><%= review.rating %><br>
    <strong>Content:</strong> <%= review.content %><br><br><br>
  <% end %>
<% else %>
  <center>
    Looks like you haven't written any reviews yet.
  </center>
<% end %>