config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/users/:id/reviews', to: 'users#reviews', as: 'users_reviews'
  get '/users/:id/highest_rated_books', to: 'users#highest_rated_books', as: 'users_highest_rated_books'
  get '/users/:id/lowest_rated_books', to: 'users#lowest_rated_books', as: 'users_lowest_rated_books'

  resources :books do
    resources :reviews
  end

  resources :book_lists do
    resources :books, only: [:create, :destroy, :new, :edit, :update]
  end

  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :book_features
  has_many :book_lists, :through => :book_features
  has_many :reviews
  has_many :users, :through => :reviews

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :author_id, presence: true
  validates :genre_id, presence: true
  before_validation :make_title_case

  scope :highest_rated_books, -> { joins(:reviews).where('reviews.rating > 3') }
  scope :lowest_rated_books, -> { joins(:reviews).where('reviews.rating <= 3') }
  scope :by_user, ->(user) { joins(:reviews).where('reviews.user_id = ?', user.id ) }
  scope :alphabatize, -> { order('title asc') }

  def self.search(term)
    self.find_by(title: term.titlecase)
  end

  def make_title_case
    self.title = self.title.titlecase
  end

  def genre_name=(name)
    self.genre = Genre.find_or_create_by(name: name)
  end

  def genre_name
    if self.genre
      self.genre.name
    end
  end

  def author_name=(name)
    self.author = Author.find_or_create_by(name: name)
  end

  def author_name
    if self.author
      self.author.name
    end
  end

  def book_list_id=(id)
    book_list = BookList.find_by(id: id)
    if !self.book_lists.include?(book_list)
      self.book_lists << book_list
    end
  end

  def book_list_ids=(ids)
    ids.each do |id|
      book_list = BookList.find_by(id: id)
      if !book_list.books.include?(self)
        book_list.books << self
      end
    end
  end

  def update_status(status, book_list_id: nil, book_list_ids: nil)
    if book_list_id != nil
      book_feature = BookFeature.find_by(book_id: self.id, book_list_id: book_list_id)
      book_feature.update_columns(status: status)
    end

    if book_list_ids != nil
      book_list_ids.each do |book_list|
        new_book_list = BookList.find_by(id: book_list)
        book_feature = BookFeature.find_by(book_id: self.id, book_list_id: new_book_list.id)
        book_feature.update_columns(status: status)
      end
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  validates :name, presence: true
  before_validation :make_title_case
  scope :alphabatize, -> { order('name asc') }

  def make_title_case
    self.name = self.name.titlecase
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :book_lists
  has_many :reviews

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def books
    users_books = []
    BookList.where(user_id: self.id).each do |booklist|
        booklist.books.each do |book|
          users_books << book
      end
    end
    users_books
  end

  def books_by_status(status)
    books_by_status = []
    BookList.where(user_id: self.id).each do |booklist|
      BookFeature.where(book_list_id: booklist.id).each do |book|
        if book.status == "#{status}"
          new_book = Book.find_by(id: book.book_id)
          books_by_status << new_book
        end
      end
    end
    books_by_status
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_current_user

  def index
    @books = Book.alphabatize
    if params[:term].present?
      @searched_book = Book.search(params[:term])
      if !@searched_book.nil?
        redirect_to book_path(@searched_book)
      else
        flash[:notice] = "Sorry that book doesn't exist"
        render 'books/index'
      end
    end
  end

  def new
    authorize! :create, Book
    @book = Book.new
    @booklist = BookList.find_by(id: params[:book_list_id])
    authorize! :update, @booklist
  end

  def create
    @book = Book.create(book_params)
    @booklist = BookList.find_by(id: params[:book][:book_list_id])
    if @book.save
      update_book_statuses
      redirect_to book_list_path(@booklist)
    else
      @booklist = BookList.find_by(id: params[:book][:book_list_id])
      render :new
    end
  end

  def show
    @book = Book.find_by(id: params[:id])
    if current_user
      @book_on_booklist = @book.book_lists.where(user_id: current_user.id)
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
    @booklist = BookList.find_by(id: params[:book_list_id])
    authorize! :update, @booklist
  end

  def update
    @book = Book.find_by(id: params[:id])
    @book.update(book_params)
    update_book_statuses
    if params[:book][:book_list_id].present?
      @booklist = BookList.find_by(id: params[:book][:book_list_id])
      redirect_to book_list_path(@booklist)
    else
      redirect_to book_path(@book.id)
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @booklist = BookList.find_by(id: params[:book_list_id])
    @booklist.books.delete(@book.id)
    flash[:notice] = "Book was deleted from your booklist"
    redirect_to book_list_path(@booklist)
  end

  private
    def book_params
      params.require(:book).permit(:term, :book_list_id, :title, :genre_name, :author_name, :book_features => [], :book_list_ids => [])
    end

    def set_current_user
      @user = current_user
    end

    def update_book_statuses
      if params[:book][:book_list_ids].present?
        @book.update_status(params[:book][:book_features], book_list_ids: params[:book][:book_list_ids])
      end

      if params[:book][:book_list_id].present?
        @book.update_status(params[:book][:book_features], book_list_id: params[:book][:book_list_id])
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_booklists.html.erb
<%= form_for booklist do |f| %>
  <%= f.label "Select a book from the list below:" %><br>
  <%= f.collection_check_boxes :book_ids, Book.all, :id, :title, :checked => false do |b|%>
    <%= b.check_box %><%= b.label %><br>
  <% end %><br>
  <%= f.label "Status" %><br>
  <%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%><br><br>
  <%= f.submit "Select this book"%>
<% end %>

app/views/books/_book_status.html.erb
<%= form_for book do |f| %>
  <strong>
  <%= f.label "Change the status:" %>
  </strong><br>
  <%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%>
  <br>
  <br>
  <%= f.hidden_field :book_list_id, :value => booklist.id %>
  <%= f.submit %>
<% end %>

app/views/books/_booklist_book_collection.html.erb
<%= form_for booklist do |f| %>

  <%= f.label "Select a book from the list below:" %><br>
  <%= f.collection_check_boxes :book_ids, Book.alphabatize, :id, :title, :checked => false, :include_hidden => false do |b|%>
    <%= b.check_box %><%= b.label %><br>
  <% end %><br>

  <%= f.label "Status" %><br>
  <%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%><br><br>

  <%= f.submit "Select this book"%>
<% end %>

app/views/books/_booklistcollection.html.erb
<%= form_for book do |f| %>
  <%= f.collection_check_boxes :book_list_ids, user.book_lists, :id, :title, :checked => false, :include_hidden => false do |b| %>
    <%= b.check_box %><%= b.label %><br>
  <% end %>
  <br>

  <%= f.label "Status " %><br>
  <%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%><br><br>

  <%= f.submit "Add to this booklist"%>
<% end %>

app/views/books/_form.html.erb
<%= form_for book do |f| %>

  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label "Genre" %><br>
  <%= f.text_field :genre_name %><br><br>

  <%= f.label "Author" %><br>
  <%= f.text_field :author_name %><br><br>

  <%= f.label "Status" %><br>
  <%= f.select :book_features, [["Currently reading"], ["Already read"], ["Want to read"]]%><br><br>

  <%= f.hidden_field :book_list_id, :value => booklist.id %>
  <%= f.submit "Add this book to your booklist"%>

<% end %>

app/views/books/edit.html.erb
<%= render partial: 'layouts/errors', locals: {object: @book} %>

<h1>Update the status of: "<%= @book.title %>"</h1>
<strong>Title: </strong><%= @book.title %><br>
<strong>Genre: </strong><%= @book.genre_name %><br>
<strong>Author: </strong><%= @book.author_name %><br><br>

<%= render partial: 'book_status', locals: {book: @book, booklist: @booklist} %>

app/views/books/index.html.erb
<h2>Books</h2>
<%= form_tag(books_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %><br>
  <%= submit_tag 'Search For A Book By Title', name: nil %>
<% end %>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book.id) %></li>
<% end %>
</ul>

app/views/books/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @book} %>

<h2>Create A New Book To Add To "<%= @booklist.title %>"</h1>
<%= render partial: 'form', locals: {book: @book, booklist: @booklist} %>
<br>
<hr>
<h2>Add An Existing Book To "<%= @booklist.title %>"</h2>
<%= render partial: 'booklist_book_collection', locals: {booklist: @booklist} %>

app/views/books/show.html.erb
<center>
  <h1><%= @book.title %></h1>
  Author: <%= link_to @book.author.name, author_path(@book.author) %> ||
  Genre: <%= link_to @book.genre.name, genre_path(@book.genre) %> ||
  <%= link_to "Reviews", book_reviews_path(@book) %>
  <hr>
</center>

<% if current_user && @book_on_booklist.present? %>
  <h3>This book appears on these book lists:</h3>
    <% @book_on_booklist.each do |book_list| %>
      <%= link_to book_list.title, book_list_path(book_list) %><br>
    <% end %>
<% end %>

<% if current_user && current_user.book_lists.present? %>
<h3>Add it to one of your book lists:</h3>
  <%= render partial: "booklistcollection", locals: {book: @book, user: @user} %>
<% end %>
<br>

<center>
  <%= link_to "Add A Review", new_book_review_path(@book.id) %>
</center>