config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/users/:id/reviews', to: 'users#reviews', as: 'users_reviews'
  get '/users/:id/highest_rated_books', to: 'users#highest_rated_books', as: 'users_highest_rated_books'
  get '/users/:id/lowest_rated_books', to: 'users#lowest_rated_books', as: 'users_lowest_rated_books'

  resources :books do
    resources :reviews
  end

  resources :book_lists do
    resources :books, only: [:create, :destroy, :new, :edit, :update]
  end

  resources :authors, only: [:index, :show]
  resources :genres, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
    <ul>
    <%= object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav>
  <hr>
    <center>
      <% if current_user %>
        <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
      <% end %>
    </center>
</nav>

app/views/layouts/_header.html.erb
<nav>
  <center>
    <h1>
      <u> The Great Listby </u>
      </h1>
        <%= link_to "Home", root_path %> | <%= link_to "All Books", books_path %> | <%= link_to "All Authors", authors_path %> | <%= link_to "All Genres", genres_path %>
        <% if current_user %>
          |  <%= link_to "New Book List", new_book_list_path %> | <%= link_to "Your book lists", book_lists_path %> | <%= link_to "Your reviews", users_reviews_path(current_user) %></a>
          | <%= link_to "Highest Rated Books", users_highest_rated_books_path(current_user) %> | <%= link_to "Lowest Rated Books", users_lowest_rated_books_path(current_user) %></a>
        <% end %>
      <hr>
  </center>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Great Listby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Goudy+Bookletter+1911|Open+Sans" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>